
platform_url = 'https://platform-in.risksense.com'

# Specify the path to the folder containing the files you wish to upload.
# If you update this, please use the absolute path to your desired folder.
json_filename = 'bandit-report.json'
folder = 'reports/'

# Trigger URBA upon completion of upload processing.
#auto_urba = true

# You may uncomment this parameter and enter the desired network ID for your upload here if you already know it.
#network_id = 155014
network_name = 'devsectest'

# You may uncomment this parameter and enter the desired client ID for your upload here if you already know it.
client_id = 100
