name: workflow_name

on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out self
      uses: actions/checkout@v3
    - name: Self sast-scan
      uses: AppThreat/sast-scan-action@1.0.2
      with:
        src: /github/workspace/work
        type: reports
    - name: Upload scan reports
      uses: actions/upload-artifact@v1.0.0
      with:
        name: sast-scan-reports
        path: python
    - name: Upload to RS
      env:
        RS_API_KEY: ${{ secrets.RS_API_KEY}}
      run:
          | 
          python -m pip install toml
          python python/AppThreatUpload.py
   
