name: workflow_name

on: [push]

jobs:
  build-secure-and-push:
    runs-on: self-hosted
    steps:
    - name: Self sast-scan
      uses: AppThreat/sast-scan-action@1.0.2
      with:
        src: /github/workspace/test/work
        output: reports
        type: python
    - name: Upload scan reports
      uses: actions/upload-artifact@v1.0.0
      with:
        name: sast-scan-reports
        path: reports
   
